declare var logo: any;
declare var navlogo: any;
declare var navlogosimple: any;
declare var sign: any;
declare var techIcon: any;
declare var clockIcon: any;
declare var clockOffIcon: any;
declare var requestSymbol: any;
declare var downArrow: any;
declare var plusSymbol: any;
declare var sendSymbol: any;
declare var signoutSymbol: any;
declare var settingsSymbol: any;
declare var commsSymbol: any;
declare var commsSymbolNot: any;
declare var cameraSymbol: any;
declare var calendar: any;
export { logo, navlogo, navlogosimple, sign, techIcon, clockIcon, clockOffIcon, requestSymbol, downArrow, plusSymbol, sendSymbol, signoutSymbol, settingsSymbol, commsSymbol, commsSymbolNot, cameraSymbol, calendar, };
