var logo = require('../../assets/logo.jpg');
var navlogo = require('../../assets/navlogo.png');
var navlogosimple = require('../../assets/navlogosimple.png');
var sign = require('../../assets/sign.png');
var techIcon = require('../../assets/techIcon.png');
var clockIcon = require('../../assets/clock.png');
var clockOffIcon = require('../../assets/clockOff.png');
var requestSymbol = require('../../assets/requestSymbol.png');
var downArrow = require('../../assets/downArrow.png');
var plusSymbol = require('../../assets/plusSymbol.png');
var sendSymbol = require('../../assets/sendSymbol.png');
var signoutSymbol = require('../../assets/signoutSymbol.png');
var settingsSymbol = require('../../assets/settingsSymbol.png');
var commsSymbol = require('../../assets/commsSymbol.png');
var commsSymbolNot = require('../../assets/commsSymbolNot.png');
var cameraSymbol = require('../../assets/camera.png');
var calendar = require('../../assets/calendar.png');
export { logo, navlogo, navlogosimple, sign, techIcon, clockIcon, clockOffIcon, requestSymbol, downArrow, plusSymbol, sendSymbol, signoutSymbol, settingsSymbol, commsSymbol, commsSymbolNot, cameraSymbol, calendar, };
//# sourceMappingURL=Index.js.map