"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.calendar = exports.cameraSymbol = exports.commsSymbolNot = exports.commsSymbol = exports.settingsSymbol = exports.signoutSymbol = exports.sendSymbol = exports.plusSymbol = exports.downArrow = exports.requestSymbol = exports.clockOffIcon = exports.clockIcon = exports.techIcon = exports.sign = exports.navlogosimple = exports.navlogo = exports.logo = void 0;
var logo = require("./logo.jpg");
exports.logo = logo;
var navlogo = require("./navlogo.png");
exports.navlogo = navlogo;
var navlogosimple = require("./navlogosimple.png");
exports.navlogosimple = navlogosimple;
var sign = require("./sign.png");
exports.sign = sign;
var techIcon = require("./techIcon.png");
exports.techIcon = techIcon;
var clockIcon = require("./clock.png");
exports.clockIcon = clockIcon;
var clockOffIcon = require("./clockOff.png");
exports.clockOffIcon = clockOffIcon;
var requestSymbol = require("./requestSymbol.png");
exports.requestSymbol = requestSymbol;
var downArrow = require("./downArrow.png");
exports.downArrow = downArrow;
var plusSymbol = require("./plusSymbol.png");
exports.plusSymbol = plusSymbol;
var sendSymbol = require("./sendSymbol.png");
exports.sendSymbol = sendSymbol;
var signoutSymbol = require("./signoutSymbol.png");
exports.signoutSymbol = signoutSymbol;
var settingsSymbol = require("./settingsSymbol.png");
exports.settingsSymbol = settingsSymbol;
var commsSymbol = require("./commsSymbol.png");
exports.commsSymbol = commsSymbol;
var commsSymbolNot = require("./commsSymbolNot.png");
exports.commsSymbolNot = commsSymbolNot;
var cameraSymbol = require("./camera.png");
exports.cameraSymbol = cameraSymbol;
var calendar = require("./calendar.png");
exports.calendar = calendar;
