"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.calendar = exports.cameraSymbol = exports.commsSymbolNot = exports.commsSymbol = exports.settingsSymbol = exports.signoutSymbol = exports.sendSymbol = exports.plusSymbol = exports.downArrow = exports.requestSymbol = exports.clockOffIcon = exports.clockIcon = exports.techIcon = exports.sign = exports.navlogosimple = exports.navlogo = exports.logo = void 0;
var logo = require("../../assets/logo.jpg");
exports.logo = logo;
var navlogo = require("../../assets/navlogo.png");
exports.navlogo = navlogo;
var navlogosimple = require("../../assets/navlogosimple.png");
exports.navlogosimple = navlogosimple;
var sign = require("../../assets/sign.png");
exports.sign = sign;
var techIcon = require("../../assets/techIcon.png");
exports.techIcon = techIcon;
var clockIcon = require("../../assets/clock.png");
exports.clockIcon = clockIcon;
var clockOffIcon = require("../../assets/clockOff.png");
exports.clockOffIcon = clockOffIcon;
var requestSymbol = require("../../assets/requestSymbol.png");
exports.requestSymbol = requestSymbol;
var downArrow = require("../../assets/downArrow.png");
exports.downArrow = downArrow;
var plusSymbol = require("../../assets/plusSymbol.png");
exports.plusSymbol = plusSymbol;
var sendSymbol = require("../../assets/sendSymbol.png");
exports.sendSymbol = sendSymbol;
var signoutSymbol = require("../../assets/signoutSymbol.png");
exports.signoutSymbol = signoutSymbol;
var settingsSymbol = require("../../assets/settingsSymbol.png");
exports.settingsSymbol = settingsSymbol;
var commsSymbol = require("../../assets/commsSymbol.png");
exports.commsSymbol = commsSymbol;
var commsSymbolNot = require("../../assets/commsSymbolNot.png");
exports.commsSymbolNot = commsSymbolNot;
var cameraSymbol = require("../../assets/camera.png");
exports.cameraSymbol = cameraSymbol;
var calendar = require("../../assets/calendar.png");
exports.calendar = calendar;
